CREATE TABLE MESSAGE(
    ID NUMBER PRIMARY KEY,
    TEXT VARCHAR2(300),
    DATE_SEND TIMESTAMP,
    DATE_READ TIMESTAMP,
    USER_FROM NUMBER,
    CONSTRAINT USERF_FK FOREIGN KEY (USER_FROM)
    REFERENCES USER_PROFILE(ID),
    USER_TO NUMBER,
    CONSTRAINT USERT_FK FOREIGN KEY (USER_TO)
    REFERENCES USER_PROFILE(ID)
);