CREATE TABLE POST(
    ID NUMBER PRIMARY KEY,
    MESSAGE VARCHAR2(200),
    DATE_POSTED TIMESTAMP,
    LOCATION VARCHAR2(100),
    USER_POSTED NUMBER,
    CONSTRAINT USERP_FK FOREIGN KEY (USER_POSTED)
    REFERENCES USER_PROFILE(ID),
    USER_PAGE_POSTED NUMBER,
    CONSTRAINT USERTO_FK FOREIGN KEY (USER_PAGE_POSTED)
    REFERENCES USER_PROFILE(ID)
);

CREATE SEQUENCE POST_SK START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE TABLE USERS_TAGGED(
  ID NUMBER PRIMARY KEY ,
  POST_ID NUMBER,
  CONSTRAINT POST_ID_FK FOREIGN KEY (POST_ID)
  REFERENCES POST(ID),
  TAGGED_ID NUMBER,
  CONSTRAINT TAGGED_ID_FK FOREIGN KEY (TAGGED_ID)
  REFERENCES USER_PROFILE(ID)
)