CREATE TABLE POST(
    ID NUMBER PRIMARY KEY,
    MESSAGE VARCHAR2(200),
    DATE_POSTED TIMESTAMP,
    LOCATION VARCHAR2(100),
    USER_POSTED NUMBER,
    CONSTRAINT USERP_FK FOREIGN KEY (USER_POSTED)
    REFERENCES USER_PROFILE(ID),
    USER_PAGE_POSTED NUMBER,
    CONSTRAINT USERP_FK FOREIGN KEY (USER_POSTED)
    REFERENCES USER_PROFILE(ID)
);

CREATE SEQUENCE POST_SK START WITH 1 INCREMENT BY 1 NOMAXVALUE;