CREATE TABLE POST(
    ID NUMBER PRIMARY KEY,
    MESSAGE VARCHAR2(500),
    DATE_POSTED TIMESTAMP,
    USER_POSTED NUMBER,
    CONSTRAINT USERP_FK FOREIGN KEY (USER_POSTED)
    REFERENCES USER_PROFILE(ID)
);