CREATE TABLE RELATIONSHIP{
  ID_USER_FROM  NUMBER,
  CONSTRAINT REL_USER_FROM FOREIGN KEY (ID_USER_FROM)
  REFERENCES USER(ID),
  ID_USER_TO NUMBER ,
  CONSTRAINT REL_USER_TO FOREIGN KEY (ID_USER_TO)
  REFERENCES USER(ID),
  RELATES VARCHAR2(50)
  }