CREATE TABLE RELATIONSHIP(
  ID NUMBER PRIMARY KEY ,
  ID_USER_FROM  NUMBER,
  CONSTRAINT REL_USER_FROM FOREIGN KEY (ID_USER_FROM)
  REFERENCES USER_PROFILE(ID),
  ID_USER_TO NUMBER ,
  CONSTRAINT REL_USER_TO FOREIGN KEY (ID_USER_TO)
  REFERENCES USER_PROFILE(ID),
  RELATES VARCHAR2(20) CHECK( RELATES IN ('FRIEND','FORMERFRIEND','REQUESTSEND','REQUESTDECLINE') )
  );

CREATE SEQUENCE RELATE_SK START WITH 1 INCREMENT BY 1 NOMAXVALUE;

ALTER TABLE RELATIONSHIP ADD LAST_CHANGES TIMESTAMP;