CREATE TABLE USER_PROFILE(
ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
PHONE VARCHAR2(50),
COUNRY VARCHAR2(50),
CITY VARCHAR2(50),
AGE INT,
DATE_REGISTERED TIMESTAMP,
LAST_ACTIVE TIMESTAMP,
STATUS VARCHAR2(50),
RELIGION VARCHAR2(50),
SCHOOL VARCHAR2(100),
UNIVERSITY VARCHAR2(100)
);